{
 "title": "Faucet Metrics",
 "time": { "from": "now-15m", "to": "now" },
 "panels": [
  {
   "title": "Balance",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    { "expr": "faucet_balance_eth", "legendFormat": "balance" }
   ]
  },
  {
   "title": "Nonces",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    { "expr": "faucet_nonce_latest", "legendFormat": "latest_nonce" },
    { "expr": "faucet_nonce_pending", "legendFormat": "nonce_pending" }
   ]
  },
  {
   "title": "claim requests",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "sum(faucet_http_requests_total{path=\"/api/claim\", code = \"200\"})",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum by (reason) (faucet_filtered_requests_total{path=\"/api/claim\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "avg req duration",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "targets": [
    {
     "expr": "avg(rate(faucet_http_request_duration_seconds_sum{path=\"/api/claim\"}[5m]) / rate(faucet_http_request_duration_seconds_count{path=\"/api/claim\"}[5m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "requests by status",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "targets": [
    {
     "expr": "sum by (code)(faucet_http_requests_total{path=\"/api/claim\"}) ",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}